import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import '../../styles/globals.css';
import MainContext from '@/providers/MainContext';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainContext>
          <div className="flex flex-col flex-1 h-[100vh]">
            <Header params={params} />
            <main className="flex-col flex-1">{children}</main>
            <Footer />
          </div>
        </MainContext>
      </body>
    </html>
  );
}
